name: Update Slicer Presets

on:
    schedule:
        -   cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    update_slicer_presets:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup Git
                run: |
                    git config --global user.name "github-actions[bot]"
                    git config --global user.email "github-actions[bot]@users.noreply.github.com"

            -   name: Run update script
                run: |
                    pip install -r requirements.txt
                    python load_profiles.py

            -   name: Commit changes
                run: |
                    git add .
                    if git commit -m "Update presets"; then
                        git push origin
                    fi